<?php
/**
 * Template Name: Privacy Policy
 *
 * @package Maria_Charalambous_Ivanova
 */

get_header();

$clinic_image_base = 'https://davidb1646.sg-host.com/wp-content/uploads/2026/02/';
?>

<main id="main" class="site-main">

	<!-- Hero -->
	<section class="privacy-hero" style="background-image: url('<?php echo esc_url( $clinic_image_base . 'dental-art-clinic-by-dr-maria-charalambous-ivanova-reception-lobby-clinic-name.avif' ); ?>');">
		<div class="privacy-hero__overlay"></div>
		<div class="container privacy-hero__content">
			<h1 class="privacy-hero__title fade-in fade-in-delay-0">Privacy Policy</h1>
			<p class="privacy-hero__subtitle fade-in fade-in-delay-1">How we collect, use, and protect your personal information.</p>
		</div>
	</section>

	<!-- Privacy Content -->
	<section class="page-section page-section--surface">
		<div class="container">
			<div class="privacy-content fade-in fade-in-delay-0">

				<p>Dental Art Clinic by Dr. Maria Charalambous-Ivanova ("we", "us", or "our") operates the website dentalartcliniclimassol.com. This Privacy Policy explains how we collect, use, and safeguard your personal data when you visit our website or use our services, in accordance with the General Data Protection Regulation (GDPR) and the Cyprus Processing of Personal Data (Protection of the Individual) Law.</p>

				<h2>Data Controller</h2>
				<p>The data controller responsible for your personal data is:</p>
				<p>
					Dr. Maria Charalambous-Ivanova<br>
					Dental Art Clinic<br>
					PRIMO AMARI, Walter Gropius 49-49, Floor 1, Apt. 101<br>
					Limassol 3076, Cyprus<br>
					Email: <a href="mailto:info@dentalartcliniclimassol.com">info@dentalartcliniclimassol.com</a><br>
					Phone: <a href="tel:+35725377757">+357 25 377757</a>
				</p>

				<h2>Information We Collect</h2>

				<h3>Information You Provide</h3>
				<p>When you book an appointment or submit a contact form on our website, we collect:</p>
				<ul>
					<li>Full name</li>
					<li>Phone number</li>
					<li>Selected service of interest</li>
					<li>Any additional information you include in your message</li>
				</ul>

				<h3>Information Collected Automatically</h3>
				<p>When you visit our website, we automatically collect certain information through Google Analytics, including:</p>
				<ul>
					<li>IP address (anonymised)</li>
					<li>Browser type and version</li>
					<li>Operating system</li>
					<li>Pages visited, time spent on pages, and navigation paths</li>
					<li>Referring website or source</li>
					<li>Device type (desktop, mobile, or tablet)</li>
					<li>Approximate geographic location (city/country level)</li>
				</ul>

				<h2>How We Use Your Information</h2>
				<p>We use the information we collect for the following purposes:</p>
				<ul>
					<li>To respond to your enquiries and schedule appointments</li>
					<li>To provide dental care and maintain treatment records as required by law</li>
					<li>To communicate with you about your treatment or upcoming appointments</li>
					<li>To analyse website traffic and improve our website experience through Google Analytics</li>
					<li>To comply with our legal and regulatory obligations</li>
				</ul>

				<h2>Legal Basis for Processing</h2>
				<p>We process your personal data on the following legal grounds:</p>
				<ul>
					<li><strong>Consent:</strong> When you submit a contact or appointment form, you consent to us processing your data for the purpose of responding to your enquiry.</li>
					<li><strong>Contractual necessity:</strong> Processing is necessary to provide dental services you have requested.</li>
					<li><strong>Legal obligation:</strong> We are required to maintain patient records in compliance with Cyprus healthcare regulations.</li>
					<li><strong>Legitimate interest:</strong> We use Google Analytics to understand how visitors use our website so we can improve it. This processing is based on our legitimate interest in maintaining and enhancing our online presence.</li>
				</ul>

				<h2>Google Analytics</h2>
				<p>This website uses Google Analytics, a web analytics service provided by Google LLC. Google Analytics uses cookies to help us analyse how visitors use our website. The information generated by the cookie about your use of the website is transmitted to and stored by Google on servers in the United States.</p>
				<p>We have enabled IP anonymisation, which means your IP address is truncated before being transmitted to Google. Google will use this information to evaluate your use of the website, compile reports on website activity, and provide other services related to website usage.</p>
				<p>You can prevent Google Analytics from collecting your data by installing the <a href="https://tools.google.com/dlpage/gaoptout" target="_blank" rel="noopener noreferrer">Google Analytics Opt-out Browser Add-on</a>.</p>
				<p>For more information on how Google handles your data, please refer to <a href="https://policies.google.com/privacy" target="_blank" rel="noopener noreferrer">Google's Privacy Policy</a>.</p>

				<h2>Cookies</h2>
				<p>Our website uses cookies to ensure proper functionality and to collect analytics data. The cookies we use include:</p>
				<ul>
					<li><strong>Essential cookies:</strong> Required for the website to function correctly, such as form submission and session handling.</li>
					<li><strong>Analytics cookies:</strong> Set by Google Analytics to distinguish users and track website usage patterns. These cookies include <code>_ga</code>, <code>_ga_*</code>, and expire after 2 years and 24 hours respectively.</li>
				</ul>
				<p>You can control or delete cookies through your browser settings. Disabling cookies may affect the functionality of some parts of the website.</p>

				<h2>Data Sharing</h2>
				<p>We do not sell, trade, or rent your personal information. We may share your data with:</p>
				<ul>
					<li><strong>Google LLC:</strong> Through Google Analytics, for the purpose of website analytics (subject to Google's privacy policy).</li>
					<li><strong>Hosting provider:</strong> Our website is hosted by SiteGround, which processes data on our behalf under appropriate data processing agreements.</li>
					<li><strong>Regulatory authorities:</strong> When required by law, such as for compliance with healthcare regulations in Cyprus.</li>
				</ul>

				<h2>Data Retention</h2>
				<p>We retain your personal data only for as long as necessary to fulfil the purposes for which it was collected:</p>
				<ul>
					<li><strong>Contact form submissions:</strong> Retained for up to 12 months, unless the enquiry leads to a patient relationship.</li>
					<li><strong>Patient records:</strong> Retained in accordance with Cyprus healthcare record-keeping requirements (minimum 10 years after the last treatment).</li>
					<li><strong>Analytics data:</strong> Google Analytics data is retained for 14 months, after which it is automatically deleted.</li>
				</ul>

				<h2>Your Rights</h2>
				<p>Under the GDPR, you have the following rights regarding your personal data:</p>
				<ul>
					<li><strong>Right of access:</strong> You can request a copy of the personal data we hold about you.</li>
					<li><strong>Right to rectification:</strong> You can ask us to correct inaccurate or incomplete data.</li>
					<li><strong>Right to erasure:</strong> You can request deletion of your personal data, subject to legal retention requirements.</li>
					<li><strong>Right to restrict processing:</strong> You can ask us to limit how we use your data.</li>
					<li><strong>Right to data portability:</strong> You can request your data in a structured, machine-readable format.</li>
					<li><strong>Right to object:</strong> You can object to processing based on legitimate interest, including analytics.</li>
					<li><strong>Right to withdraw consent:</strong> Where processing is based on consent, you can withdraw it at any time.</li>
				</ul>
				<p>To exercise any of these rights, please contact us at <a href="mailto:info@dentalartcliniclimassol.com">info@dentalartcliniclimassol.com</a> or call <a href="tel:+35725377757">+357 25 377757</a>.</p>
				<p>You also have the right to lodge a complaint with the Office of the Commissioner for Personal Data Protection in Cyprus at <a href="https://www.dataprotection.gov.cy" target="_blank" rel="noopener noreferrer">www.dataprotection.gov.cy</a>.</p>

				<h2>Data Security</h2>
				<p>We implement appropriate technical and organisational measures to protect your personal data against unauthorised access, alteration, disclosure, or destruction. Our website uses SSL/TLS encryption to secure data transmitted between your browser and our server.</p>

				<h2>Third-Party Links</h2>
				<p>Our website may contain links to external websites, including Google Maps and social media platforms. We are not responsible for the privacy practices of these third-party websites and encourage you to read their privacy policies.</p>

				<h2>Changes to This Policy</h2>
				<p>We may update this Privacy Policy from time to time to reflect changes in our practices or legal requirements. Any changes will be posted on this page with an updated revision date. We encourage you to review this page periodically.</p>

				<p><strong>Last updated:</strong> March 2026</p>

			</div>
		</div>
	</section>

	<!-- CTA Banner -->
	<section class="about-cta" style="background-image: url('<?php echo esc_url( $clinic_image_base . 'dental-art-clinic-by-dr-maria-charalambous-ivanova-treatment-room-wide-angle-equipment.avif' ); ?>');">
		<div class="about-cta__overlay"></div>
		<div class="container about-cta__content">
			<h2 class="fade-in fade-in-delay-0">Have Questions About <span class="accent-font">Your Data?</span></h2>
			<p class="fade-in fade-in-delay-1">We are happy to answer any questions about how we handle your personal information.</p>
			<div class="about-cta__buttons fade-in fade-in-delay-2">
				<a href="<?php echo esc_url( home_url( '/contact/' ) ); ?>" class="btn btn-primary">Contact Us</a>
				<a href="tel:+35725377757" class="btn btn-outline-light">Call +357 25 377757</a>
			</div>
		</div>
	</section>

</main>

<?php get_footer(); ?>
